### ISSUE TITLE
shields -> dependencies broken

### ISSUE THREAD

**Issue by mralexgray** [mosjs/mos#92]
in README.md...
```md
<!--@shields('dependencies')-->
<!--/@-->
```

results in...
> `Error: Failed to execute template code at line 5 with '`dependencies` shield is not supported'`
> `    at /Volumes/5T/ServiceData/node/need/node_modules/mos-plugin-ejs/dist/index.js:65:23`

**Comment by zkochan** [comment]
Try `deps`

```
<!--@shields('deps')-->
<!--/@-->
```

[Here are](https://github.com/zkochan/shieldman/blob/master/lib/shields-list.js) the currently available shields. The keys are the shield names

**Comment by mralexgray** [comment]
@zkochan  yes, i realized shortly thereafter... however the docs need to be fixed...

> Add this code snippet to your README.md

> `<!--@shields('travis', 'dependencies')-->`
> `<!--/@-->`
