### ISSUE TITLE
How does mos install plugins?

### ISSUE THREAD

**Issue by Luidog** [mosjs/mos#95]
Hello,

Thank you for the awesome project. I seem to be having trouble using a mos plugin:

https://github.com/aitherios/mos-plugin-execute

after installing the plugin and attempting to use the plugin with mos I get the following error:

`execute('echo', ['works'])
Error: Failed to execute template code at line 240 with 'execute is not defined'`

I checked to see that the plugin module name is prefixed with 'mod-plugin' and 'mos-plugin' is a keyword but it seems that I can not get the package to be included. Can you point me to where in the codebase mos searches for and installs plugins?

**Comment by zkochan** [comment]
@Luidog  in the `package.json` where you installed mos and your plugin, add this field:

```json
"mos": {
  "plugins": ["execute"]
}
```

> sorry, I neglected this project a bit because I concentrated all my attention on [pnpm](https://github.com/pnpm/pnpm)

**Comment by Luidog** [comment]
@zkochan Thank you! This is a great project.
